### ISSUE TITLE
Performance and accuracy

### ISSUE THREAD

**Issue by chentairan** [cv-core/tensorrt_ros#1]
Hi All,

As mentioned in your paper, you use Nvidia xavier to run TensorRT for network inference. I would like to ask if you use int8 and what is the accuracy of int8's YoloV3. And have you used two dla to speed up inference ?

Best,
Tairan Chen

**Comment by Sibozhu** [comment]
Hi Tairan, 
Thank you for your interest in our project.

> if you use int8

Yes, we do use int8.

> what is the accuracy of int8's YoloV3

We never actually measured it, but it performs similarly to our YoloV3 without quantization.

> have you used two dla to speed up inference

Yes

**Comment by chentairan** [comment]
Thank you for your reply !

Best,
Tairan Chen
