### ISSUE TITLE
YOLOv4 or YOLOv5 support

### ISSUE THREAD

**Issue by chentairan** [cv-core/tensorrt_ros#2]
Hi,
With the release of YOLOv4 and YOLOv5 this year, the real-time and accuracy of object detection has been improved to a new level. Is there any plan to support for TensorRT of YOLOv4 or YOLOv5 in ROS?

Best,
Tairan Chen

**Comment by Sibozhu** [comment]
Sorry, we will not participate in Formula Student Competitions this year so it won't come out soon.
